spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/duke_blog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Duke@0417
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:/home/files

duke:
  sqllog:
    enabled: true
  redisson:
    enabled: false
  swagger:
    enabled: true #开启swagger,默认为开启
    title: blog api
    description: 博客项目服务
    version:
    termsOfServiceUrl:
    license:
    licenseUrl:
    basePackage: com.duke.microservice.blog
  blog:
    storage:
      path: /home/files
      max-upload-size: 1024
      #文本类型文件后缀
      text-type: txt,sql,java,js,html,xml,html,css
      #图片类型文件后缀
      img-type: jpeg,jpg,png,bmp
      #office文件类型后缀
      office-type: doc,docx,xlsx,xls,ppt,pptx
      #压缩文件类型后缀
      compress-type: zip,rar,jar,gzip
      #pdf文件
      pdf-type: pdf
      qiniu:
        accessKey: V2gvMcNpvtCDaIpHisRH3Yy2zTNi6KI0ZmvoW24N
        secretKey: 8uZC6BRXqHRHJ6XL-degwFVM8y_VZr6pwJSIbfJX
        bucket: duke-blog  #创建的存储空间名
        path:     #存储空间的访问域名

security:
  oauth2:
    resource:
      user-info-uri: http://dukehu.top:5285/user/duke-blog
