server:
  port: 5286
  context-path: /

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/duke_blog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: duke
    hikari:
      data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

security:
  user:
    name: duke
    password: duke
  basic:
    enabled: false
  oauth2:
    resource:
      service-id: duke-auth
      user-info-uri: http://localhost:5285/user

management:
  security:
    enabled: false
  context-path: /management

logging:
  file: ./logs/blog.log
  level:
    root: info

debug: true

duke:
  sqllog:
    enabled: true
  redisson:
    enabled: false
  swagger:
    enabled: true #开启swagger,默认为开启
    title: blog api
    description: 博客项目服务
    version:
    termsOfServiceUrl:
    license:
    licenseUrl:
    basePackage: com.duke.microservice.blog

mybatis:
    mapper-locations: classpath*:mapper/**/*Mapper.xml
