server:
  port: 5286
  context-path: /

spring:
  profiles:
    active: @profileActive@
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

security:
  user:
    name: duke
    password: duke
  basic:
    enabled: false
  oauth2:
    resource:
      service-id: duke-auth
      user-info-uri: http://localhost:5285/auth/user/duke-blog

management:
  security:
    enabled: false
  context-path: /management

logging:
  file: ./logs/blog.log
  level:
    root: info
    #com.duke.microservice.blog.mapper: debug

debug: true

mybatis:
    mapper-locations: classpath*:mapper/**/*Mapper.xml
